server:
  port: 9090
  
spring:
  application:
    name: Turbine

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
    service-url:
      default-zone: http://localhost:8761/eureka/

turbine:
  app-config: Ribbon-Consumer-With-CircuitBreaker, Feign-Consumer-With-CircuitBreaker, Feign-Consumer-With-CircuitBreaker-Through-Zuul, API-Gateway
  cluster-name-expression: "'default'"